// app
export const TOGGLE_MOBILE_VIEW = "TOGGLE_MOBILE_VIEW";

export const GET_ALL_POLICIES = "GET_ALL_POLICIES";

//account
export const GET_EXPENSES_ACC_HEAD = "GET_EXPENSES_ACC_HEAD";
export const GET_EXPENSES_ACC_HEAD_LOADING = "GET_EXPENSES_ACC_HEAD_LOADING";
export const GET_PATIENT_LIST = "GET_PATIENT_LIST";
export const SET_PATIENTS = "SET_PATIENTS";
